# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'example' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket'
  ]

  pod 'react-native-vkontakte-login', :path => '../node_modules/react-native-vkontakte-login'

  target 'exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
